config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */
use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 * Cache: Routes are cached to improve performance, check the RoutingMiddleware
 * constructor in your `src/Application.php` file to change this behavior.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    // Register scoped middleware for in scopes.
    $routes->registerMiddleware('csrf', new CsrfProtectionMiddleware([
        'httpOnly' => true
    ]));

    /**
     * Apply a middleware to the current route scope.
     * Requires middleware to be registered via `Application::routes()` with `registerMiddleware()`
     */
    $routes->applyMiddleware('csrf');

    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'dashboard']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *
     * ```
     * $routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);
     * $routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);
     * ```
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * Router::scope('/api', function (RouteBuilder $routes) {
 *     // No $routes->applyMiddleware() here.
 *     // Connect API actions here.
 * });
 * ```
 */

src/Model/Entity/Quotation.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;
use Cake\ORM\TableRegistry;
/**
 * Quotation Entity
 *
 * @property int $id
 * @property int $customer_id
 * @property string $quotation_number
 * @property float $value
 * @property string $reference
 * @property string $address
 * @property int $cap
 * @property string $city
 * @property string $status
 * @property \Cake\I18n\FrozenDate $quotation_date
 * @property string $balance_note
 * @property string $commission
 * @property int $archived
 * @property string|null $order_number
 * @property string $ referent
 *
 * @property \App\Model\Entity\Customer $customer
 * @property \App\Model\Entity\Action[] $actions
 * @property \App\Model\Entity\OrdersCustomer[] $orders_customers
 * @property \App\Model\Entity\Upload[] $uploads
 */
class Quotation extends Entity
{
    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true
    ];
  
    protected function _getLabel()
    {
        //pr($this);
        
        $customers = TableRegistry::get('Customers');
        $customers = $customers->find('all')
          ->where(['id' => ($this->_properties['customer_id'])]);
        
        $customers = $customers->first();
        $this->set(compact('customers'));
            
        return "Rif. impianto: ".$this->_properties['reference'] . ' - Data prev: ' . $this->_properties['quotation_date'] ." - ". $customers->name;
    }
}

src/Model/Table/QuotationsTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Quotations Model
 *
 * @property \App\Model\Table\CustomersTable|\Cake\ORM\Association\BelongsTo $Customers
 * @property \App\Model\Table\ActionsTable|\Cake\ORM\Association\HasMany $Actions
 * @property \App\Model\Table\OrdersCustomersTable|\Cake\ORM\Association\HasMany $OrdersCustomers
 * @property |\Cake\ORM\Association\HasMany $OrdersSuppliers
 * @property \App\Model\Table\UploadsTable|\Cake\ORM\Association\HasMany $Uploads
 * @property |\Cake\ORM\Association\BelongsToMany $Suppliers
 *
 * @method \App\Model\Entity\Quotation get($primaryKey, $options = [])
 * @method \App\Model\Entity\Quotation newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Quotation[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Quotation|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Quotation saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Quotation patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Quotation[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Quotation findOrCreate($search, callable $callback = null, $options = [])
 */
class QuotationsTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('quotations');
        $this->setDisplayField('label');
        $this->setPrimaryKey('id');

        $this->belongsTo('Customers', [
            'foreignKey' => 'customer_id',
            'joinType' => 'INNER'
        ]);
      
        $this->belongsTo('Professionals', [
          'foreignKey' => 'professional_2',
          'joinType' => 'INNER'
        ]);
        
        $this->belongsTo('Professionals', [
          'foreignKey' => 'professional_1',
          'joinType' => 'INNER'
        ]);
      
        $this->hasMany('Actions', [
            'foreignKey' => 'quotation_id'
        ]);
        $this->hasMany('OrdersCustomers', [
            'foreignKey' => 'quotation_id'
        ]);
        $this->hasMany('OrdersSuppliers', [
            'foreignKey' => 'quotation_id'
        ]);
//         $this->hasMany('Uploads', [
//             'foreignKey' => 'quotation_id'
//         ]);
        $this->belongsToMany('Suppliers', [
            'foreignKey' => 'quotation_id',
            'targetForeignKey' => 'supplier_id',
            'joinTable' => 'quotations_suppliers'
        ]);
      
        //proffer plugin per upload file al preventivo cliente
        $this->hasMany('Uploads', [
            'foreignKey' => 'quotation_id'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
//         $validator
//             ->integer('id')
//             ->allowEmptyString('id', 'create');

//         $validator
//             ->scalar('quotation_number')
//             ->maxLength('quotation_number', 255)
//             ->requirePresence('quotation_number', 'create')
//             ->allowEmptyString('quotation_number', false);

//         $validator
//             ->decimal('value')
//             ->requirePresence('value', 'create')
//             ->allowEmptyString('value', false);

//         $validator
//             ->scalar('reference')
//             ->maxLength('reference', 255)
//             ->requirePresence('reference', 'create')
//             ->allowEmptyString('reference', false);

//         $validator
//             ->scalar('address')
//             ->maxLength('address', 255)
//             ->requirePresence('address', 'create')
//             ->allowEmptyString('address', false);

//         $validator
//             ->integer('cap')
//             ->requirePresence('cap', 'create')
//             ->allowEmptyString('cap', false);

//         $validator
//             ->scalar('city')
//             ->maxLength('city', 255)
//             ->requirePresence('city', 'create')
//             ->allowEmptyString('city', false);

//         $validator
//             ->scalar('status')
//             ->maxLength('status', 255)
//             ->requirePresence('status', 'create')
//             ->allowEmptyString('status', false);

//         $validator
//             ->date('quotation_date')
//             ->requirePresence('quotation_date', 'create')
//             ->allowEmptyDate('quotation_date', false);

//         $validator
//             ->scalar('balance_note')
//             ->maxLength('balance_note', 255)
//             ->requirePresence('balance_note', 'create')
//             ->allowEmptyString('balance_note', false);

//         $validator
//             ->scalar('commission')
//             ->maxLength('commission', 255)
//             ->requirePresence('commission', 'create')
//             ->allowEmptyString('commission', false);

//         $validator
//             ->scalar('order_number')
//             ->maxLength('order_number', 255)
//             ->allowEmptyString('order_number');

//         $validator
//             ->scalar(' referent')
//             ->maxLength(' referent', 255)
//             ->requirePresence(' referent', 'create')
//             ->allowEmptyString(' referent', false);

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['customer_id'], 'Customers'));

        return $rules;
    }
}

src/Template/Quotations/add.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Quotation $quotation
 */
?>

<div class="card bg-white card-shadow new-contact">
    <div class="card-body">
         <h3><?= __('Aggiungi preventivo contatto') ?></h3>
          <br/>
          <?= $this->Form->create($quotation) ?>
          <fieldset>
            <div class="row">
<!--               <div class="col-md-3">
                  <div class="form-group">
                          <?php //echo $this->Form->control('quotation_number' , ['label' => 'Numero preventivo']);?>
                      <i class="form-group__bar"></i>
                  </div>
              </div> -->
              <div class="col-md-3">
                  <div class="form-group">
                      <?php //controllo se c'è un customer_id passato dalla view di customer
                          if (isset($customer_id)) { 
                              echo $this->Form->control('customer_name' , ['label' => 'Contatto', 
                                                                         'value' => $customer_detail,
                                                                        'type' => 'text',
                                                                        'readonly' => 'readonly']);
                              echo $this->Form->control('customer_id',['value' => $customer_id,'type' => 'hidden']);
                         // se non c'è customer_id chiedo a quale cliente associare il preventivo
                         } else {
                              echo $this->Form->control('customer_id' , 
                                  ['options' => $customers, 'label' => 'Seleziona il contatto','empty' => 'Scegli il nome...']);
 
                         } ?>
                      <i class="form-group__bar"></i>
                  </div>
              </div>
               <div class="col-md-6">
                  <div class="form-group">
                          <?php echo $this->Form->control('reference' , ['label' => 'Tipo impianto']);?>
                      <i class="form-group__bar"></i>
                  </div>
              </div>
            </div>
            <div class="row">
<!--                <div class="col-md-3">
                  <div class="form-group">
                          <?php //echo $this->Form->control('quotation_number' , ['label' => 'Indica il numero del preventivo']);?>
                      <i class="form-group__bar"></i>
                  </div>
              </div> -->
              <div class="col-md-3">
                  <div class="form-group">
                          <?php echo $this->Form->control('value' , ['label' => 'Importo preventivo']);?>
                      <i class="form-group__bar"></i>
                  </div>
              </div>
              <div class="col-md-3">
                  <div class="form-group">
                          <?php echo $this->Form->control('commission' , ['label' => 'Prevista commissione']);?>
                      <i class="form-group__bar"></i>
                  </div>
              </div>
              <div class="col-md-4">
                  <div class="form-group">
                          <?php echo $this->Form->control('address' , ['label' => 'Indirizzo installazione']);?>
                      <i class="form-group__bar"></i>
                  </div>
              </div>
              <div class="col-md-4">
                  <div class="form-group">
                          <?php echo $this->Form->control('cap' , ['label' => 'CAP']);?>
                      <i class="form-group__bar"></i>
                  </div>
              </div>
               <div class="col-md-4">
                  <div class="form-group">
                          <?php echo $this->Form->control('city' , ['label' => 'Città installazione']);?>
                      <i class="form-group__bar"></i>
                  </div>
              </div>
              <div class="col-md-4">
                  <div class="form-group">
                          <?php echo $this->Form->control('status' , ['label' => 'Stato preventivo', 'options' => $quotationStatusList,'empty' => 'indica lo stato preventivo']);?>
                      <i class="form-group__bar"></i>
                  </div>
              </div>
              <div class="col-md-4">
                  <div class="form-group">
                          <?php echo $this->Form->control('quotation_date' , ['label' => 'Data preventivo']);?>
                      <i class="form-group__bar"></i>
                  </div>
              </div>
             <div class="col-md-4">
                  <div class="form-group">
                          <?php echo $this->Form->control('balance_note' , ['label' => 'Note aggiuntive']);?>
                      <i class="form-group__bar"></i>
                  </div>
              </div>
               <div class="col-md-4">
                  <div class="form-group">
                          <?php echo $this->Form->control('referent' , ['label' => 'Committente',"placeholder"=>"Indicare la persona di riferimento del futuro ordine",]);?>
                      <i class="form-group__bar"></i>
                  </div>
              </div>
                             <div class="col-md-4">
                  <div class="form-group">
                          <?php echo $this->Form->control('professional_1' , ['options' => $professionals,'label' => 'Professionista 1','empty' => 'indica un professionista']);?>
                      <i class="form-group__bar"></i>
                  </div>
              </div>
                             <div class="col-md-4">
                  <div class="form-group">
                          <?php echo $this->Form->control('professional_2' , ['options' => $professionals,'label' => 'Professionista 2','empty' => 'indica un professionista']);?>
                      <i class="form-group__bar"></i>
                  </div>
              </div>
<!--               <div class="col-md-4">
                  <div class="form-group">
                          <?php echo $this->Form->control('supplier' , ['label' => 'Supplier']);?>
                          <?php echo $this->Form->control('archived',['value' => 0,'type' => 'hidden']);?>
                      <i class="form-group__bar"></i>
                  </div>
              </div> -->
            </div>
        </fieldset>
       <!--<?= $this->Form->create($uploadOrder,['type' => 'file']) ?>-->
                                            <fieldset>
                                              <legend>Uploads</legend>
                                              <?php 
                                              echo $this->Form->control('filename', ['type' => 'file','required'=>false,'multiple' => false,'class' => 'form-control','label' => '']);
                                              //echo $this->Form->hidden('order_customer_id', ['value'=>$orderDetailValues->id]);
                                              //echo $this->Form->hidden('order_number', ['value'=>$orderDetailValues->order_number]);
                                              echo $this->Form->hidden('quotation_id', ['value'=>$quotation->id]);
                                              echo $this->Form->control('docfolder' , ['value'=>'Preventivo']);
                                              ?>
                                            </fieldset>
                                            <!--<?= $this->Form->button(__('Salva'), ['class' => 'btn btn-primary']) ?>-->
                                            <!--<?= $this->Form->end() ?>-->
     <?= $this->Form->button(__('Salva'), ['class' => 'btn btn-primary']) ?>
    <?= $this->Form->end() ?>
  </div>
</div>

src/Template/Quotations/archived.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Supplier[]|\Cake\Collection\CollectionInterface $suppliers
 */
?>
<div class="card bg-white card-shadow">
    <div class="card-body">
        <h3><?= __('Elenco preventivi clienti ARCHIVIATI') ?></h3>
            <table class="table table-responsive" id="data-table" >
            <thead class="thead-light">
            <tr>
                <th scope="col"><?= h('Tipo impianto') ?></th>
                <th scope="col"><?= h('Indirizzo')?></th>
                <th scope="col"><?= h('Città') ?></th>
                <th scope="col"><?= h('Cliente') ?></th>
                <th scope="col"><?= h('Stato preventivo') ?></th>
                <th scope="col"><?= h('Data preventivo') ?></th>
                <th scope="col"><?= h('Importo preventivo') ?></th>
<!--                 <th scope="col"><?= h('Ordine cliente generato') ?></th>        -->
            </tr>
        </thead>
        <tbody>
            <?php foreach ($quotations as $quotation): ?>
            <tr>
                <td><?= $this->Html->link(__($quotation->reference), ['action' => 'view', $quotation->id]) ?></td>
                <td><?= h($quotation->address) ?></td>
                <td><?= h($quotation->city) ?></td>
                <td><?= $quotation->has('customer') ? $this->Html->link($quotation->customer->name, ['controller' => 'Customers', 'action' => 'view', $quotation->customer->id]) : '' ?></td>
                <td><? switch ($quotation->status) 
                              {
                                case '9':
                                echo "in preparazione";
                                break;
                                case '8':
                                echo "chiuso perso";
                                break;
                                case '7':
                                echo "chiuso vinto";
                                break;
                                case '6':
                                echo "quasi perso";
                                break;
                                case '5':
                                echo "non prevedibile";
                                break;
                                case '4':
                                echo "in corso";
                                break;
                                case '3':
                                echo "probabile vinto";
                                break;
                                case '2':
                                echo "quasi vinto medio periodo";
                                break;
                                case '1':
                                echo "quasi vinto breve periodo";
                                break;
                                default:
                                echo "----";
                                break;
                              }
                     ?>
                </td>
                <td><?= h($quotation->quotation_date) ?></td>
                <td><?= h($this->Number->currency($quotation->value, "EUR")) ?></td>
<!--                 <td><?= h($quotation->order_number) ?></td> -->
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
</div>

src/Template/Quotations/index.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Supplier[]|\Cake\Collection\CollectionInterface $suppliers
 */
?>
<div class="card bg-white card-shadow">
    <div class="card-body">
        <h3><?= __('Elenco preventivi clienti') ?></h3>
            <table class="table table-responsive" id="data-table" >
            <thead class="thead-light">
            <tr>
                <th><?= h('Dettaglio') ?></th>
                <th scope="col"><?= h('Tipo impianto') ?></th>
                <th scope="col"><?= h('Indirizzo')?></th>
                <th scope="col"><?= h('Città') ?></th>
                <th scope="col"><?= h('Cliente') ?></th>
                <th scope="col"><?= h('Committente') ?></th>   
                <th scope="col"><?= h('Professionista 1') ?></th>
                <th scope="col"><?= h('Professionista 2') ?></th>
               <th scope="col"><?= h('Stato preventivo') ?></th>
                <th scope="col"><?= h('Data preventivo') ?></th>
                <th scope="col"><?= h('Importo preventivo') ?></th>       
            </tr>
        </thead>
        <tbody>
            <?php foreach ($quotations as $quotation): ?>
            <tr>
                <td><?= $this->Html->link(__("Visualizza"), ['action' => 'view', $quotation->id]) ?></td>
                <td><?= $this->Html->link(__($quotation->reference), ['action' => 'view', $quotation->id]) ?></td>
                <td><?= h($quotation->address) ?></td>
                <td><?= h($quotation->city) ?></td>
                <td><?= $quotation->has('customer') ? $this->Html->link($quotation->customer->name, ['controller' => 'Customers', 'action' => 'view', $quotation->customer->id]) : '' ?></td>
                <td><?= h($quotation->referent) ?></td>
                <td><?= $quotation->has('professional_1') ? $this->Html->link($professionalsList[$quotation->professional_1], ['controller' => 'Professionals', 'action' => 'view', $quotation->professional->id]) : '' ?></td>
                <td><?= $quotation->has('professional_2') ? $this->Html->link($professionalsList[$quotation->professional_2], ['controller' => 'Professionals', 'action' => 'view', $quotation->professional->id]) : '' ?></td>
                <td><?= h($quotation->status) ?></td>  
              <?php  
//                  $numero_settings = count($quotationStatusList) - 1;
//                  for ($i = 0; $i <= $numero_settings; $i++) 
//                  {
//                    if($quotation->status == $quotationStatusList[$i]->id )
//                    {
//                      echo "<td>".($quotationStatusList[$i]->description)."</td>";
//                    }
//                    else
//                    {
//                      //echo "<td><p>test</p></td>";
//                    }
//                  }
                ?>
                <td><?= h($quotation->quotation_date) ?></td>
                <td><?= h($this->Number->currency($quotation->value, "EUR")) ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
</div>