config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */
use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 * Cache: Routes are cached to improve performance, check the RoutingMiddleware
 * constructor in your `src/Application.php` file to change this behavior.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    // Register scoped middleware for in scopes.
    $routes->registerMiddleware('csrf', new CsrfProtectionMiddleware([
        'httpOnly' => true
    ]));

    /**
     * Apply a middleware to the current route scope.
     * Requires middleware to be registered via `Application::routes()` with `registerMiddleware()`
     */
    $routes->applyMiddleware('csrf');

    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'dashboard']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *
     * ```
     * $routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);
     * $routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);
     * ```
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * Router::scope('/api', function (RouteBuilder $routes) {
 *     // No $routes->applyMiddleware() here.
 *     // Connect API actions here.
 * });
 * ```
 */

src/Model/Entity/OrderPhase2.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * OrderPhase2 Entity
 *
 * @property int $order_id
 * @property int $phase_completed
 * @property string $description_step_1
 * @property \Cake\I18n\FrozenDate $step_1_created
 * @property int $step_1_completed
 * @property \Cake\I18n\FrozenDate $step_1_completedtime
 * @property string $description_step_2
 * @property \Cake\I18n\FrozenDate $step_2_created
 * @property int $step_2_completed
 * @property \Cake\I18n\FrozenDate $step_2_completedtime
 * @property string $description_step_3
 * @property \Cake\I18n\FrozenDate $step_3_created
 * @property int $step_3_completed
 * @property \Cake\I18n\FrozenDate $step_3_completedtime
 * @property string $description_step_4
 * @property \Cake\I18n\FrozenDate $step_4_created
 * @property int $step_4_completed
 * @property \Cake\I18n\FrozenDate $step_4_completedtime
 * @property string $description_step_5
 * @property \Cake\I18n\FrozenDate $step_5_created
 * @property int $completed_step_5
 * @property int $step_5_completedtime
 * @property string $description_step_6
 * @property \Cake\I18n\FrozenDate $step_6_created
 * @property int $completed_step_6
 * @property int $step_6_completedtime
 * @property string $description_step_7
 * @property \Cake\I18n\FrozenDate $step_7_created
 * @property int $completed_step_7
 * @property int $step_7_completedtime
 * @property string $description_step_8
 * @property \Cake\I18n\FrozenDate $step_8_created
 * @property int $completed_step_8
 * @property int $step_8_completedtime
 * @property string $description_step_9
 * @property \Cake\I18n\FrozenDate $step_9_created
 * @property int $completed_step_9
 * @property int $step_9_completedtime
 *
 * @property \App\Model\Entity\Order $order
 */
class OrderPhase2 extends Entity
{
    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        'phase_completed' => true,
        'description_step_1' => true,
        'step_1_created' => true,
        'step_1_completed' => true,
        'step_1_completedtime' => true,
        'description_step_2' => true,
        'step_2_created' => true,
        'step_2_completed' => true,
        'step_2_completedtime' => true,
        'description_step_3' => true,
        'step_3_created' => true,
        'step_3_completed' => true,
        'step_3_completedtime' => true,
        'description_step_4' => true,
        'step_4_created' => true,
        'step_4_completed' => true,
        'step_4_completedtime' => true,
        'description_step_5' => true,
        'step_5_created' => true,
        'completed_step_5' => true,
        'step_5_completedtime' => true,
        'description_step_6' => true,
        'step_6_created' => true,
        'completed_step_6' => true,
        'step_6_completedtime' => true,
        'description_step_7' => true,
        'step_7_created' => true,
        'completed_step_7' => true,
        'step_7_completedtime' => true,
        'description_step_8' => true,
        'step_8_created' => true,
        'completed_step_8' => true,
        'step_8_completedtime' => true,
        'description_step_9' => true,
        'step_9_created' => true,
        'completed_step_9' => true,
        'step_9_completedtime' => true,
        'order' => true,
        'step_1_user' => true, 
        'step_2_user' => true, 
        'step_3_user' => true, 
        'step_4_user' => true, 
        'step_5_user' => true, 
        'step_6_user' => true, 
        'step_7_user' => true, 
        'step_8_user' => true, 
        'step_9_user' => true,
        'step_1_notes' => true,
        'step_2_notes' => true,
        'step_3_notes' => true,
        'step_4_notes' => true,
        'step_5_notes' => true,
        'step_6_notes' => true,
        'step_7_notes' => true,
        'step_8_notes' => true,
        'step_9_notes' => true
    ];
}

src/Model/Table/OrderPhase2Table.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * OrderPhase2 Model
 *
 * @method \App\Model\Entity\OrderPhase2 get($primaryKey, $options = [])
 * @method \App\Model\Entity\OrderPhase2 newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\OrderPhase2[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\OrderPhase2|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\OrderPhase2 saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\OrderPhase2 patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\OrderPhase2[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\OrderPhase2 findOrCreate($search, callable $callback = null, $options = [])
 */
class OrderPhase2Table extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('order_phase2');
        $this->setDisplayField('order_id');
        $this->setPrimaryKey('order_id');
      
      
      
        $this->belongsTo('OrdersCustomers', [
            'foreignKey' => 'order_id',
            'joinType' => 'INNER'
        ]);
      
      
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('order_id')
            ->allowEmptyString('order_id', 'create');

        $validator
            ->integer('phase_completed')
            ->requirePresence('phase_completed', 'create')
            ->allowEmptyString('phase_completed', false);

        $validator
            ->scalar('description_step_1')
            ->maxLength('description_step_1', 255)
            ->requirePresence('description_step_1', 'create')
            ->allowEmptyString('description_step_1', false);

        $validator
            ->date('step_1_created')
            ->requirePresence('step_1_created', 'create')
            ->allowEmptyDate('step_1_created', false);

        $validator
            ->integer('step_1_completed')
            ->requirePresence('step_1_completed', 'create')
            ->allowEmptyString('step_1_completed', false);

        $validator
            ->date('step_1_completedtime')
            ->requirePresence('step_1_completedtime', 'create')
            ->allowEmptyDate('step_1_completedtime', false);

        $validator
            ->scalar('description_step_2')
            ->maxLength('description_step_2', 255)
            ->requirePresence('description_step_2', 'create')
            ->allowEmptyString('description_step_2', false);

        $validator
            ->date('step_2_created')
            ->requirePresence('step_2_created', 'create')
            ->allowEmptyDate('step_2_created', false);

        $validator
            ->integer('step_2_completed')
            ->requirePresence('step_2_completed', 'create')
            ->allowEmptyString('step_2_completed', false);

        $validator
            ->date('step_2_completedtime')
            ->requirePresence('step_2_completedtime', 'create')
            ->allowEmptyDate('step_2_completedtime', false);

        $validator
            ->scalar('description_step_3')
            ->maxLength('description_step_3', 255)
            ->requirePresence('description_step_3', 'create')
            ->allowEmptyString('description_step_3', false);

        $validator
            ->date('step_3_created')
            ->requirePresence('step_3_created', 'create')
            ->allowEmptyDate('step_3_created', false);

        $validator
            ->integer('step_3_completed')
            ->requirePresence('step_3_completed', 'create')
            ->allowEmptyString('step_3_completed', false);

        $validator
            ->date('step_3_completedtime')
            ->requirePresence('step_3_completedtime', 'create')
            ->allowEmptyDate('step_3_completedtime', false);

        $validator
            ->scalar('description_step_4')
            ->maxLength('description_step_4', 255)
            ->requirePresence('description_step_4', 'create')
            ->allowEmptyString('description_step_4', false);

        $validator
            ->date('step_4_created')
            ->requirePresence('step_4_created', 'create')
            ->allowEmptyDate('step_4_created', false);

        $validator
            ->integer('step_4_completed')
            ->requirePresence('step_4_completed', 'create')
            ->allowEmptyString('step_4_completed', false);

        $validator
            ->date('step_4_completedtime')
            ->requirePresence('step_4_completedtime', 'create')
            ->allowEmptyDate('step_4_completedtime', false);

        $validator
            ->scalar('description_step_5')
            ->maxLength('description_step_5', 255)
            ->requirePresence('description_step_5', 'create')
            ->allowEmptyString('description_step_5', false);

        $validator
            ->date('step_5_created')
            ->requirePresence('step_5_created', 'create')
            ->allowEmptyDate('step_5_created', false);

        $validator
            ->integer('completed_step_5')
            ->requirePresence('completed_step_5', 'create')
            ->allowEmptyString('completed_step_5', false);

        $validator
            ->integer('step_5_completedtime')
            ->requirePresence('step_5_completedtime', 'create')
            ->allowEmptyString('step_5_completedtime', false);

        $validator
            ->scalar('description_step_6')
            ->maxLength('description_step_6', 255)
            ->requirePresence('description_step_6', 'create')
            ->allowEmptyString('description_step_6', false);

        $validator
            ->date('step_6_created')
            ->requirePresence('step_6_created', 'create')
            ->allowEmptyDate('step_6_created', false);

        $validator
            ->integer('completed_step_6')
            ->requirePresence('completed_step_6', 'create')
            ->allowEmptyString('completed_step_6', false);

        $validator
            ->integer('step_6_completedtime')
            ->requirePresence('step_6_completedtime', 'create')
            ->allowEmptyString('step_6_completedtime', false);

        $validator
            ->scalar('description_step_7')
            ->maxLength('description_step_7', 255)
            ->requirePresence('description_step_7', 'create')
            ->allowEmptyString('description_step_7', false);

        $validator
            ->date('step_7_created')
            ->requirePresence('step_7_created', 'create')
            ->allowEmptyDate('step_7_created', false);

        $validator
            ->integer('completed_step_7')
            ->requirePresence('completed_step_7', 'create')
            ->allowEmptyString('completed_step_7', false);

        $validator
            ->integer('step_7_completedtime')
            ->requirePresence('step_7_completedtime', 'create')
            ->allowEmptyString('step_7_completedtime', false);

        $validator
            ->scalar('description_step_8')
            ->maxLength('description_step_8', 255)
            ->requirePresence('description_step_8', 'create')
            ->allowEmptyString('description_step_8', false);

        $validator
            ->date('step_8_created')
            ->requirePresence('step_8_created', 'create')
            ->allowEmptyDate('step_8_created', false);

        $validator
            ->integer('completed_step_8')
            ->requirePresence('completed_step_8', 'create')
            ->allowEmptyString('completed_step_8', false);

        $validator
            ->integer('step_8_completedtime')
            ->requirePresence('step_8_completedtime', 'create')
            ->allowEmptyString('step_8_completedtime', false);

        $validator
            ->scalar('description_step_9')
            ->maxLength('description_step_9', 255)
            ->requirePresence('description_step_9', 'create')
            ->allowEmptyString('description_step_9', false);

        $validator
            ->date('step_9_created')
            ->requirePresence('step_9_created', 'create')
            ->allowEmptyDate('step_9_created', false);

        $validator
            ->integer('completed_step_9')
            ->requirePresence('completed_step_9', 'create')
            ->allowEmptyString('completed_step_9', false);

        $validator
            ->integer('step_9_completedtime')
            ->requirePresence('step_9_completedtime', 'create')
            ->allowEmptyString('step_9_completedtime', false);

        return $validator;
    }
}

src/Template/OrderPhase2/add.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\OrderPhase2 $orderPhase2
 */
?>
<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Actions') ?></li>
        <li><?= $this->Html->link(__('List Order Phase2'), ['action' => 'index']) ?></li>
    </ul>
</nav>
<div class="orderPhase2 form large-9 medium-8 columns content">
    <?= $this->Form->create($orderPhase2) ?>
    <fieldset>
        <legend><?= __('Add Order Phase2') ?></legend>
        <?php
            echo $this->Form->control('phase_completed');
            echo $this->Form->control('description_step_1');
            echo $this->Form->control('step_1_created');
            echo $this->Form->control('step_1_completed');
            echo $this->Form->control('step_1_completedtime');
            echo $this->Form->control('description_step_2');
            echo $this->Form->control('step_2_created');
            echo $this->Form->control('step_2_completed');
            echo $this->Form->control('step_2_completedtime');
            echo $this->Form->control('description_step_3');
            echo $this->Form->control('step_3_created');
            echo $this->Form->control('step_3_completed');
            echo $this->Form->control('step_3_completedtime');
            echo $this->Form->control('description_step_4');
            echo $this->Form->control('step_4_created');
            echo $this->Form->control('step_4_completed');
            echo $this->Form->control('step_4_completedtime');
            echo $this->Form->control('description_step_5');
            echo $this->Form->control('step_5_created');
            echo $this->Form->control('completed_step_5');
            echo $this->Form->control('step_5_completedtime');
            echo $this->Form->control('description_step_6');
            echo $this->Form->control('step_6_created');
            echo $this->Form->control('completed_step_6');
            echo $this->Form->control('step_6_completedtime');
            echo $this->Form->control('description_step_7');
            echo $this->Form->control('step_7_created');
            echo $this->Form->control('completed_step_7');
            echo $this->Form->control('step_7_completedtime');
            echo $this->Form->control('description_step_8');
            echo $this->Form->control('step_8_created');
            echo $this->Form->control('completed_step_8');
            echo $this->Form->control('step_8_completedtime');
            echo $this->Form->control('description_step_9');
            echo $this->Form->control('step_9_created');
            echo $this->Form->control('completed_step_9');
            echo $this->Form->control('step_9_completedtime');
        ?>
    </fieldset>
    <?= $this->Form->button(__('Submit')) ?>
    <?= $this->Form->end() ?>
</div>

src/Template/OrderPhase2/order_status.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Supplier[]|\Cake\Collection\CollectionInterface $suppliers
 */
?>
<div class="card bg-white card-shadow">
    <div class="card-body">
        <h3><?= __('Elenco ordini clienti da attenzionare') ?></h3>
            <table class="table table-responsive" id="data-table" >
              <br/>
              <h3>Ordini in fase 2</h3>
            <thead class="thead-light">
            <tr>
                <th scope="col"><?= h('Numero ordine') ?></th>
                <th scope="col"><?= h('Numero impianto')?></th>
                <th scope="col"><?= h('Data ordine') ?></th>
                <th scope="col"><?= h('Cliente') ?></th>
                <th scope="col"><?= h('Indirizzo') ?></th>
                <th scope="col"><?= h('Step da eseguire') ?></th>
                <th scope="col"><?= h('Descrizione step da eseguire') ?></th>
                <th scope="col"><?= h('Utente incaricato') ?></th>
                <th scope="col"><?= h('Link') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($ordersToShow as $orderToShow): ?>
            <?php //pr($ordersToShow); ?>
            <?php
                  if($orderToShow->step_1_completed == 0)
                  {
            ?>
                  <tr>
                    <td><?= h($orderToShow->orders_customer->order_number); ?></td>
                    <td><?= h($orderToShow->orders_customer->installation_number); ?></td>
                    <td><?= h($orderToShow->orders_customer->contract_sign_date); ?></td>
                    <td><?= h($orderToShow->orders_customer->customer->name); ?></td>
                    <td><?= h($orderToShow->orders_customer->quotation->address." - ".$orderToShow->orders_customer->quotation->city); ?></td>
                    <td><?//= h($orderToShow->step_1_completed); ?>1</td>
                    <td><?= h($orderToShow->description_step_1); ?></td>
                    <td>
                    <?php
                      if($orderToShow->step_1_user == 1)
                        {
                        echo "Luca";
                        }
                        elseif($orderToShow->step_1_user == 10)
                        {
                        echo "Amministrazione";
                        }
                        elseif($orderToShow->step_1_user == 100)
                        {
                        echo "Commerciale";
                        }
                        elseif($orderToShow->step_1_user == 101)
                        {
                        echo "Olti";
                        } 
                    ?>
                    </td>
                    <td><?= $this->Html->link('Visualizza dettaglio', ['controller' => 'OrderPhase1', 'action' => 'view', $orderToShow->orders_customer->id], array('id' => 'action1')) ?></td>
                  </tr>
          <?php
                 }
                  elseif($orderToShow->step_2_completed == 0)
                  {
                  ?>
                  <tr>
                    <td><?= h($orderToShow->orders_customer->order_number); ?></td>
                    <td><?= h($orderToShow->orders_customer->installation_number); ?></td>
                    <td><?= h($orderToShow->orders_customer->contract_sign_date); ?></td>
                    <td><?= h($orderToShow->orders_customer->customer->name); ?></td>
                    <td><?= h($orderToShow->orders_customer->quotation->address." - ".$orderToShow->orders_customer->quotation->city); ?></td>
                    <td><?//= h($orderToShow->step_2_completed); ?>2</td>
                    <td><?= h($orderToShow->description_step_2); ?></td>
                                        <td>
                    <?php
                      if($orderToShow->step_2_user == 1)
                        {
                        echo "Luca";
                        }
                        elseif($orderToShow->step_2_user == 10)
                        {
                        echo "Amministrazione";
                        }
                        elseif($orderToShow->step_2_user == 100)
                        {
                        echo "Commerciale";
                        }
                        elseif($orderToShow->step_2_user == 101)
                        {
                        echo "Olti";
                        } 
                    ?>
                    </td>
                    <td><?= $this->Html->link('Visualizza dettaglio', ['controller' => 'OrderPhase1', 'action' => 'view', $orderToShow->orders_customer->id], array('id' => 'action1')) ?></td>
                  </tr>
                <?php
                  }
                  elseif($orderToShow->step_3_completed == 0)
                  {
                  ?>
                  <tr>
                    <td><?= h($orderToShow->orders_customer->order_number); ?></td>
                    <td><?= h($orderToShow->orders_customer->installation_number); ?></td>
                    <td><?= h($orderToShow->orders_customer->contract_sign_date); ?></td>
                    <td><?= h($orderToShow->orders_customer->customer->name); ?></td>
                    <td><?= h($orderToShow->orders_customer->quotation->address." - ".$orderToShow->orders_customer->quotation->city); ?></td>
                    <td><?//= h($orderToShow->step_3_completed); ?>3</td>
                    <td><?= h($orderToShow->description_step_3); ?></td>
                                        <td>
                    <?php
                      if($orderToShow->step_3_user == 1)
                        {
                        echo "Luca";
                        }
                        elseif($orderToShow->step_3_user == 10)
                        {
                        echo "Amministrazione";
                        }
                        elseif($orderToShow->step_3_user == 100)
                        {
                        echo "Commerciale";
                        }
                        elseif($orderToShow->step_3_user == 101)
                        {
                        echo "Olti";
                        } 
                    ?>
                    </td>
                    <td><?= $this->Html->link('Visualizza dettaglio', ['controller' => 'OrderPhase1', 'action' => 'view', $orderToShow->orders_customer->id], array('id' => 'action1')) ?></td>
                  </tr>
                  <?
                  }
                  elseif($orderToShow->step_4_completed == 0)
                  {
                  ?>
                  <tr>
                    <td><?= h($orderToShow->orders_customer->order_number); ?></td>
                    <td><?= h($orderToShow->orders_customer->installation_number); ?></td>
                    <td><?= h($orderToShow->orders_customer->contract_sign_date); ?></td>
                    <td><?= h($orderToShow->orders_customer->customer->name); ?></td>
                    <td><?= h($orderToShow->orders_customer->quotation->address." - ".$orderToShow->orders_customer->quotation->city); ?></td>           
                    <td><?//= h($orderToShow->step_4_completed); ?>4</td>
                    <td><?= h($orderToShow->description_step_4); ?></td>
                                        <td>
                    <?php
                      if($orderToShow->step_4_user == 1)
                        {
                        echo "Luca";
                        }
                        elseif($orderToShow->step_4_user == 10)
                        {
                        echo "Amministrazione";
                        }
                        elseif($orderToShow->step_4_user == 100)
                        {
                        echo "Commerciale";
                        }
                        elseif($orderToShow->step_4_user == 101)
                        {
                        echo "Olti";
                        } 
                    ?>
                    </td>
                    <td><?= $this->Html->link('Visualizza dettaglio', ['controller' => 'OrderPhase1', 'action' => 'view', $orderToShow->orders_customer->id], array('id' => 'action1')) ?></td>
                  </tr>
                  <?
                  }
                  elseif($orderToShow->step_5_completed == 0)
                  {
                  ?>
                  <tr>
                    <td><?= h($orderToShow->orders_customer->order_number); ?></td>
                    <td><?= h($orderToShow->orders_customer->installation_number); ?></td>
                    <td><?= h($orderToShow->orders_customer->contract_sign_date); ?></td>
                    <td><?= h($orderToShow->orders_customer->customer->name); ?></td>
                    <td><?= h($orderToShow->orders_customer->quotation->address." - ".$orderToShow->orders_customer->quotation->city); ?></td>         
                    <td><?//= h($orderToShow->step_5_completed); ?>5</td>
                    <td><?= h($orderToShow->description_step_5); ?></td>
                                        <td>
                    <?php
                      if($orderToShow->step_5_user == 1)
                        {
                        echo "Luca";
                        }
                        elseif($orderToShow->step_5_user == 10)
                        {
                        echo "Amministrazione";
                        }
                        elseif($orderToShow->step_5_user == 100)
                        {
                        echo "Commerciale";
                        }
                        elseif($orderToShow->step_5_user == 101)
                        {
                        echo "Olti";
                        } 
                    ?>
                    </td>
                    <td><?= $this->Html->link('Visualizza dettaglio', ['controller' => 'OrderPhase1', 'action' => 'view', $orderToShow->orders_customer->id], array('id' => 'action1')) ?></td>
                  </tr>
                  <?
                  }?>
            <!-- fine foreach -->
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
</div>